name: Mocked-MCP
services:
  task-hub:
    container_name: mock-task-hub-mcp
    build:
      context: ..
      dockerfile: docker/task-hub.Dockerfile
    ports:
      - "3010:3010"

  crm-rest:
    container_name: mock-crm-rest
    build:
      context: ..
      dockerfile: docker/crm-rest.Dockerfile
    ports:
      - "3011:3011"

  crm-mcp:
    container_name: mock-crm-mcp
    build:
      context: ..
      dockerfile: docker/crm-mcp.Dockerfile
    ports:
      - "3012:3012"
